# ╭────────────────────ImplementationGuide-hl7.fhir.us.udap-security.json──────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.identity-matching
canonical: http://hl7.org/fhir/us/identity-matching
name: DigitalIdentity
title: "Interoperable Digital Identity and Patient Matching"
status: active
license: "CC0-1.0"
version: 2.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: STU2 Ballot
date: 2024-07-30
jurisdiction: "urn:iso:std:iso:3166#US"
publisher:
  name: HL7 International / Patient Administration
  url: http://www.hl7.org/Special/committees/pafm
dependencies:
  hl7.fhir.us.core: 6.1.0

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: pa  # <<< The value must be the code for the workgroup
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1

parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  active-tables: false
  apply-contact: true
  apply-version: true
  usage-stats-opt-out: true
  excludexml: false
  excludettl: true
  excludemap: true

pages:
  index.md:
    title: Home
  guidance-on-identity-assurance.md:
    title: Guidance on Identity Assurance
  patient-matching.md:
    title: Patient Matching
  digital-identity.md:
    title: Digital Identity
  use-cases.md:
    title: Use Cases
  industry-initiatives.md:
    title: Industry Initiatives
  downloads.md:
  glossary.md:
    title: Glossary
  changelog.md:
    title: Change Log

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Guidance on Identity Assurance: guidance-on-identity-assurance.html
  Patient Matching: patient-matching.html
  Digital Identity: digital-identity.html
  Implementation:
    Artifacts: artifacts.html
    Use Cases: use-cases.html
    Industry Initiatives: industry-initiatives.html
    Downloads: downloads.html
  Glossary: glossary.html
  Change Log: changelog.html

  
