# ╭────────────────────ImplementationGuide-hl7.fhir.us.udap-security.json──────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.identity-matching
canonical: http://hl7.org/fhir/us/identity-matching
name: DigitalIdentity
title: "Interoperable Digital Identity and Patient Matching"
status: active
license: "CC0-1.0"
version: 3.0.0-current
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: STU 3
#date: 2025-10-14
jurisdiction: "urn:iso:std:iso:3166#US"
publisher:
  name: HL7 International / Patient Administration
  url: http://www.hl7.org/Special/committees/pafm
dependencies:
  hl7.fhir.us.core: 6.1.0

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: pa  # <<< The value must be the code for the workgroup
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2

parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  active-tables: false
  apply-contact: true
  apply-version: true
  usage-stats-opt-out: true
  excludexml: false
  excludettl: false
  excludemap: true
  shownav: true
  auto-oid-root: 2.16.840.1.113883.4.642.40.81

pages:
  index.md:
    title: Home
  use-cases.md:
    title: Use Cases
  golden-identity.md:
    title: Golden Identity
  golden-design-notes.md:
    title: Golden Identity Design Notes
  golden-record-identity-design-brief.md:
    title: Golden Record Identity Design Brief
  LEI_vLEI_primer.md:
    title: LEI and vLEI Primer
  LEI_vLEI_Profiling.md:
    title: LEI and vLEI Profiling
  identity.md:
    title: Identity
  about.md:
    title: About
  glossary.md:
    title: Glossary
  industry-initiatives.md:
    title: Industry Initiatives
  changelog.md:
    title: Change Log

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Use Cases: use-cases.html
  Golden Identity: golden-identity.html
  Identity: 
    LEI and vLEI Primer: LEI_vLEI_primer.html
    LEI and vLEI Profiling: LEI_vLEI_Profiling.html
    FHIR Identity: identity.html
  Artifacts: artifacts.html
  About: 
    about: about.html
    Industry initiatives: industry-initiatives.html
    Glossary: glossary.html
    Change Log: changelog.html

  
