# ╭────────────────────ImplementationGuide-hl7.fhir.us.udap-security.json──────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.identity-matching
canonical: http://hl7.org/fhir/us/identity-matching
name: DigitalIdentity
title: "Interoperable Digital Identity and Patient Matching"
status: draft
license: "CC0-1.0"
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ballot
date: 2021-10-26
jurisdiction: "urn:iso:std:iso:3166#US"
publisher:
  name: HL7 International - Patient Administration WG
  url: http://www.hl7.org/Special/committees/pafm
dependencies:
  hl7.fhir.us.core: 3.1.1

parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  active-tables: false
  apply-contact: true
  apply-version: true
  usage-stats-opt-out: true
  excludexml: false
  excludejsn: false
  excludettl: true
  excludemap: true
  excludeexample: true

pages:
  index.md:
    title: Home
  industry-initiatives.md:
  guidance-on-identity-assurance.md:
  patient-matching.md:
    title: Patient Matching
  digital-identity.md:
    title: Digital Identity
  downloads.md:


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Industry Initiatives: industry-initiatives.html
  Guidance on Identity Assurance: guidance-on-identity-assurance.html
  Patient Matching: patient-matching.html
  Digital Identity: digital-identity.html
  Artifacts: artifacts.html
  Downloads: downloads.html

  